version: '3'
services:
  db:
    image: postgres:latest
    ports:
        - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  web:
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/yuiyui.com
    env_file:
      - ~/.env
    environment:
      POSTGRES_HOST: db
      RAILS_ENV: development
      RACK_ENV: develobpment
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  postgresql-data:
    driver: local
